### ISSUE TITLE
Change to Protobuild project

### ISSUE THREAD

**Issue by felaugmar** [Genbox/VelcroPhysics#35]
Hello :hand: 
What do you think about change the project to use [Protobuild](https://protobuild.org/) to generate the project files?

[Protobuild](https://protobuild.org/) offers some facilities and better organization for the project and is really easy to use.
:call_me_hand:

**Comment by Genbox** [comment]
I'll take a look at it in the weekend and see what it has to offer.

**Comment by ian-csis** [comment]
Looks interesting - I'm not entirely sure how to build the definition file as I have many projects depending on each other etc.

I would be happy if someone with experience in Protobuild could sketch up a solution and contribute it.

**Comment by Genbox** [comment]
Looks interesting - I'm not entirely sure how to build the definition file as I have many projects depending on each other etc.

I would be happy if someone with experience in Protobuild could sketch up a solution and contribute it.

**Comment by dsaf** [comment]
Maybe the project owner @hach-que can help?

**Comment by hach-que** [comment]
Sure, what do you need?

## Referencing another Protobuild definition or a GAC reference

Just add it to the references section like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Name="ProjectA" Path="ProjectA" Type="Library">
  <Properties />
  <References>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="ProjectB" />
  </References>
```

## Referencing DLLs in your repo, native DLLs or custom `.csproj` files

First you need to declare an external project definition (see http://protobuild.readthedocs.io/en/latest/external_projects.html for information on how these are structured and what you can do with them). Then you'd reference the external project just as you would any other Protobuild definition:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Name="ProjectA" Path="ProjectA" Type="Library">
  <Properties />
  <References>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="ExternalProject" />
  </References>
```

## Referencing NuGet packages:

First add the package to your module by running:

```
Protobuild.exe --add NameOfNuGetPackage@SpecificVersion
```

then reference the NuGet package:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Name="ProjectA" Path="ProjectA" Type="Library">
  <Properties />
  <References>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="SomeNuGetPackage" />
  </References>
```

## Referencing a Git repository

If you want to reference another Git repository that's using Protobuild (like MonoGame), you first add the Git repository as a package e.g.:

```
Protobuild.exe --add https-git://github.com/MonoGame/MonoGame@develop
```

then reference the specific projects in the package you want to pull in:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Name="ProjectA" Path="ProjectA" Type="Library">
  <Properties />
  <References>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="MonoGame.Framework" />
  </References>
```
