### ISSUE TITLE
Remove IDispose pattern in favor of RemoveFromWorld()

### ISSUE THREAD

**Issue by Genbox** [Genbox/VelcroPhysics#4]
I used IDispose it so that a user can call myBody.Dispose() and it will remove the body from the world. There are some issues with this:

1. The Disposable pattern (IDisposable) is meant for releasing unmanaged resources. Using it for anything else can have unintended consequences.
2. When an object falls out of scope, not mean the object will be garbage collected right away. Dispose() will therefore not be called until the GC comes to collect.
3. Since the World object already have a reference to the body, even when the body falls out of the current scope, it does not get garbage collected. There are tricks like [WeakReference](https://msdn.microsoft.com/en-us/library/system.weakreference(v=vs.110).aspx), but it is currently not implemented and might introduce bugs into user code, since they will need to explicitly state they need a strong reference in the World list.
4. IDispose gave the ability to use the 'using' pattern like seen below, but it is an esoteric feature since most bodies seem to be long lived.

```csharp
using (Body b = new Body(_world))
{
   //Do work with body
}

//Body will be removed from world here.
```
Instead, I propose a RemoveFromWorld() method that needs to be explicitly called whenever a body should leave the world. This is exactly the same as calling World.RemoveBody(body), but sometimes users don't have access to the World object, but do have the Body object.

Any comments, improvements or votes (thumb up/down) are appreciated.

**Comment by ilexp** [comment]
Sounds good! Especially with regard to pooling (#5), this change might also help understand users the role of the physics body as something they have to manage lifetimes of.
