### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by HughPH** [Genbox/VelcroPhysics#40]
I have attempted to port Box2D to C# twice, I also had a look at Box2DX with a view to bringing it up to date but it was much too far behind. This looks like it's in a far better state than any of those. I may contribute.

My most recent attempt to port was actually porting LiquidFun, but I got to the Particle System and found that a lot of the code is totally bizarre. There seem to be casts from classes to booleans where the cast takes a parameter(?!?!) Even then, I put compiler directives around the particle stuff but couldn't get the Box2D pieces to work nicely. (To be fair, I only spent 3 days on it.)

The reason I wanted to port it to C# was really to get it to use more than one core. The particle system is dead slow after about 4,000 particles, but it's only using 1 of my 8 logical (4 physical) cores.

So...
Once you've got this in a better state,
1. Multithreading - all collisions are evaluated at the same time, so that could be a good candidate to get started.
2. Offload to the GPU - not easy, I admit. Keeping a load of data in the GPU might be the best way forward. I'm using SFML for presentation, that provides access to GLSL but it's limited: data can only be sent as a texture, so colours are normalised from a set of four bytes to four floats. It needs a bit of 'encoding' to get anything larger in or out, and granularity of smaller numbers is limited. OpenCL would probably be the natural choice. The Campy and ILGPU libraries are worth investigating, although ILGPU is still young and the website doesn't seem to exist (I don't know if that's anymore, or yet)
3. Particles! Why not? As I mentioned, LiquidFun is already based on Box2D so there is a relevant reference implementation. And a particle system is a fantastic addition.

If I didn't need particles, I would pick this up, use it, and submit pull requests for anything I fixed. Because of my use case, I'm going to stick with LiquidFun with a C++/CLI facade in front of it. My next project probably won't need a particle system - so there's an opportunity for me to get involved there.

**Comment by Genbox** [comment]
Velcro is indeed a full port of Box2D, along with a couple of tweaks to make it a bit faster and some APIs to make it easier to use. However, it is not really API stable at the moment, so if you want something for a game, I'd recommend using Farseer Physics Engine instead.

I'd welcome any contributions.

**Comment by Genbox** [comment]
As for particles, you might want to take a look at https://github.com/Matthew-Davey/mercury-particle-engine - It is another project I used to develop together with Matt Davey. It uses shaders for all the transformations, which makes it really fast. I have not tried it in about 4 years and XNA was still a thing back then, so I'm not sure it even runs, but it had a really great design thought up by Matthew.

**Comment by HughPH** [comment]
Thanks Ian, I'll check out Mercury - although wouldn't I need to represent my world in two engines simultaneously?

I'm not too worried about API instability; you can expect that with anything that's still in development. Docker is a prime example.

**Comment by Genbox** [comment]
Only your particles would be in mercury. Although, it is possible to make Velcro interact with Mercury such that the particles have collision detection. For most games, keeping the particles and physics separate is a good idea for performance, but it depends on what you are creating.

**Comment by HughPH** [comment]
So the point of LiquidFun is really that there is interaction between particles and bodies, and the particles are sense enough to behave like liquid (hence the name).

I might have a look at the JavaScript implementation, it seems quite smooth.

I'm sure you must have come across Chris / iforce2d if you've been interested in Box2D.
https://www.youtube.com/watch?v=LAGi5x8u-c0
