### ISSUE TITLE
BodyTemplate.GravityScale is ignored

### ISSUE THREAD

**Issue by swidku** [Genbox/VelcroPhysics#47]
When creating a body with a BodyTemplate the gravity scale is completely ignored and set to 1.0 in the Body class.

**Comment by bQvle** [comment]
Dont know if its the case, but make sure every property is set after the fixture has been attached. most properties is just setters that loop through and passes it on to the fixtures. so if you add the fixture after a property has been set it might not apply to the new fixture.
