### ISSUE TITLE
MVP Sandbox

### ISSUE THREAD

**Issue by danielleedeveloper** [Genbox/VelcroPhysics#50]
I found the samples in the source to be fairly inaccessible.  I've slapped together an MVP sandbox and offer it to you for any purpose you might find useful.

[https://github.com/danielleeitny/PhysualDotNET](url)

**Comment by Genbox** [comment]
Hi Danielle,

If you upgrade the project to use the [nuget](https://www.nuget.org/packages/Genbox.VelcroPhysics/0.1.0-alpha) package, your project is automatically added to the "used by" section on github.
