### ISSUE TITLE
Upgrading from Farseer -- what do you think of Aether?

### ISSUE THREAD

**Issue by andrew-sidereal** [Genbox/VelcroPhysics#55]
I've been building my game on FSE 3.5 and finding that there have been advancements in forks, namely Velcro and Aether. I'd like to upgrade to Velcro since it's by the original author, but there are some optimizations in Aether that sound significant. What's the verdict? Does Velcro include all of Aether's optimizations, including multi-threaded support?

**Comment by alundgren04** [comment]
http://community.monogame.net/t/aether-physics2d-release-v-1-0/9709

**Comment by Genbox** [comment]
Velcro is not really in working order right now as I've removed a lot of stuff in order to rebuild it, but never got around to actually do it. It seems Aether is maintained, so It would go for that if I were you.
