### ISSUE TITLE
Importing SVG

### ISSUE THREAD

**Issue by ghost** [Genbox/VelcroPhysics#57]
Hello!
I'm facing SVGImport problems with SVG files generated with Adobe Illustrator CS6.
Here is my file: https://www.dropbox.com/s/ra0uql2eh4asfjv/terrain1.svg?dl=0

I'm using MonoGame 3.7.1 and I think that problem is here: https://github.com/VelcroPhysics/VelcroPhysics/blob/master/ContentPipeline/SVGImport/SVGPathParser.cs
in line 145

**Comment by Genbox** [comment]
I don't know what the different commands are for. Can you see which character that's not supported?

Also note that the code in this repo is under construction.

**Comment by Enter03** [comment]
In my SVG it was 's' and 'S' characters.

**Comment by Genbox** [comment]
According to [the standard](https://www.w3.org/TR/SVG/paths.html#PathDataCubicBezierCommands), it seems to be smoothed cubic bezier curves which we don't seem to support. I didn't make the SVG importer, it was a contribution from a user, so I don't know how they usually are handled.

You can try to handle them like the C and c commands and see if that works.
