### ISSUE TITLE
Question: Documentation and/or Forum

### ISSUE THREAD

**Issue by ambs** [Genbox/VelcroPhysics#66]
Quick questions:
 - Is there any documentation on the web? Or just the code?
 - Is there any forum (slack, discord, whatever) for the community to interact?
Thanks

**Comment by Genbox** [comment]
There is a discussion board here on Github: https://github.com/Genbox/VelcroPhysics/discussions
The engine itself is based on Box2D, so the documentation here cover VelcroPhysics as well: https://box2d.org/documentation/
